CloudReaderOptions:
  #pointCloudPath: "../resources/20220912_SZE(2)-001_LAS1_2_full.txt"
  pointCloudPath: "../resources/middle_horizont.csv"

  # Currently implemented: mobileMapping, groundRadar
  pointCloudType: groundRadar

CloudSorterOptions:
  pixelPerUnitX: 500000
  pixelPerUnitY: 500000
  useGPU: false

CloudRasterizerOptions:
  useGPU: false

HeightMapFillerOptions:
  useGPU: true

  # Currently implemented: closingFilter, inverseDistanceWeightedFilter
  filler: closingFilter

  kernelBasedFilterOptions:
    kernelSizes:
      - 1
    batchSize: 1024

CloudWriterOptions:
  destinationPath: "../resources/map"
  writeLowDepth: true

OpenGLOptions:
  shaderDirectory: "../shaders"