CloudReaderOptions:
  pointCloudPath: "../../res/20220912_SZE(2)-001_LAS1_2_05.txt"
  #pointCloudPath: "../resources/middle_horizont.csv"

  # Currently implemented: mobileMapping, groundRadar
  #pointCloudType: groundRadar
  pointCloudType: mobileMapping

CloudSorterOptions:
  pixelPerUnitX: 10
  pixelPerUnitY: 10
  useGPU: true

CloudRasterizerOptions:
  useGPU: true

HeightMapFillerOptions:
  useGPU: true

  # Currently implemented: closingFilter, inverseDistanceWeightedFilter
  filler: inverseDistanceWeightedFilter

  kernelBasedFilterOptions:
    kernelSizes:
      - 50
    batchSize: 1024

CloudWriterOptions:
  destinationPath: "../../res/map"
  writeLowDepth: true

OpenGLOptions:
  shaderDirectory: "../../shaders"