CloudReaderOptions:
  pointCloudPath: "../../res/20220912_SZE(2)-001_LAS1_2_05.txt"

CloudSorterOptions:
  pixelPerUnit: 20
  useGPU: true

CloudRasterizerOptions:
  useGPU: true

HeightMapFillerOptions:
  useGPU: true

  # Currently implemented: closingFilter, averageDistanceWeightedFilter
  filler: closingFilter

  kernelBasedFilterOptions:
    kernelSizes:
      - 30

CloudWriterOptions:
  destinationPath: "../../res/map"
  writeLowDepth: true