CloudReaderOptions:
  pointCloudPath: "../resources/20220912_SZE(2)-001_LAS1_2_full.txt"

CloudSorterOptions:
  pixelPerUnit: 50
  useGPU: true

CloudRasterizerOptions:
  useGPU: true

HeightMapFillerOptions:
  useGPU: true

  # Currently implemented: closingFilter, inverseDistanceWeightedFilter
  filler: closingFilter

  kernelBasedFilterOptions:
    kernelSizes:
      - 100
    batchSize: 512

CloudWriterOptions:
  destinationPath: "../resources/map"
  writeLowDepth: true

OpenGLOptions:
  shaderDirectory: "../shaders"