CloudReaderOptions:
  pointCloudPath: "../resources/20220912_SZE(2)-001_LAS1_2_full.txt"
  #pointCloudPath: "../resources/middle_horizont.csv"

  # Currently implemented: mobileMapping, groundRadar
  #pointCloudType: groundRadar
  pointCloudType: mobileMapping

CloudSorterOptions:
  pixelPerUnitX: 50
  pixelPerUnitY: 50
  useGPU: true

CloudRasterizerOptions:
  useGPU: true

HeightMapFillerOptions:
  useGPU: true

  # Currently implemented: closingFilter, inverseDistanceWeightedFilter
  filler: closingFilter

  kernelBasedFilterOptions:
    kernelSizes:
      - 5
      - 10
      - 50
    batchSize: 1024

CloudWriterOptions:
  destinationPath: "../resources/map"
  writeLowDepth: true

OpenGLOptions:
  shaderDirectory: "../shaders"