var dir_764e89aad4ba46281166d4b774e2fadd =
[
    [ "amount.glsl", "amount_8glsl.html", null ],
    [ "average.glsl", "average_8glsl.html", null ],
    [ "averageIDW.glsl", "average_i_d_w_8glsl.html", null ],
    [ "chunkSortingAndCounting.glsl", "chunk_sorting_and_counting_8glsl.html", null ],
    [ "closing.glsl", "closing_8glsl.html", null ],
    [ "compare.glsl", "compare_8glsl.html", null ],
    [ "compareSquareError.glsl", "compare_squared_error_8glsl.html", null ],
    [ "countChunks.glsl", "count_chunks_8glsl.html", null ],
    [ "dilation.glsl", "dilation_8glsl.html", null ],
    [ "discretization.glsl", "discretization_8glsl.html", null ],
    [ "erosion.glsl", "erosion_8glsl.html", null ],
    [ "horizontalAmount.glsl", "horizontal_amount_8glsl.html", null ],
    [ "horizontalSum.glsl", "horizontal_sum_8glsl.html", null ],
    [ "horizontalSumIDW.glsl", "horizontal_sum_i_d_w_8glsl.html", null ],
    [ "horizontalTotalWeights.glsl", "horizontal_total_weights_8glsl.html", null ],
    [ "kernelIDW.glsl", "kernel_i_d_w_8glsl.html", null ],
    [ "makeHeightmap.glsl", "make_heightmap_8glsl.html", null ],
    [ "radialDilation.glsl", "radial_dilation_8glsl.html", null ],
    [ "radialErosion.glsl", "radial_erosion_8glsl.html", null ],
    [ "sum.glsl", "sum_8glsl.html", null ],
    [ "sumChunks.glsl", "sum_chunks_8glsl.html", null ],
    [ "sumIDW.glsl", "sum_i_d_w_8glsl.html", null ],
    [ "totalWeights.glsl", "total_weights_8glsl.html", null ]
];